### ISSUE TITLE
What does this create?

### ISSUE THREAD

**Issue by MACscr** [phlib/schemadiff#1]
What does this create? The readme is a bit vague.

**Comment by qubit05** [comment]
Hi,

Sorry you found the Readme vague. If the following sufficiently answers your question, I'll update the description to better describe the behaviour.

The `SchemaDiff` is the main class which takes a Symfony Console `OutputInterface` as a dependency. The `diff` method uses this to output the differences between the 2 supplied schemas. The `diff` method returns a boolean true if there are differences, false otherwise.

Does this answer your question?

**Comment by jdempster** [comment]
Hi,

Thanks for your question. I've added a better description to the readme, along with some example screen shots.
